# Generated by Django 4.2.4 on 2023-08-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayListPro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='trackId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=255),
        ),
    ]
