# Generated by Django 4.2.1 on 2023-05-31 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PlayListPro", "0001_initial"),
    ]

    operations = []
