# Generated by Django 4.2.1 on 2023-05-31 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PlayListPro", "0002_auto_20230531_1341"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playlistsong",
            name="playlist",
        ),
        migrations.DeleteModel(
            name="Songs",
        ),
        migrations.DeleteModel(
            name="Playlists",
        ),
        migrations.DeleteModel(
            name="PlaylistSong",
        ),
    ]
