# Generated by Django 4.2.2 on 2023-07-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayListPro', '0003_remove_playlistsong_playlist_delete_songs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
