# Generated by Django 4.2.2 on 2023-07-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayListPro', '0006_remove_users_userid_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(db_column='name', default='', max_length=255, unique=True),
        ),
    ]
