# Generated by Django 4.2.2 on 2023-07-31 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayListPro', '0007_alter_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlistId', models.AutoField(primary_key=True, serialize=False)),
                ('playlistname', models.CharField(max_length=255)),
                ('playlistcomment', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
