# Generated by Django 4.2.2 on 2023-07-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayListPro', '0008_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='userId',
            field=models.CharField(max_length=255),
        ),
    ]
