# Generated by Django 4.2.2 on 2023-08-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlayListPro', '0009_alter_playlist_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('trackId', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('album_img', models.URLField()),
                ('artist', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=10)),
                ('playlistId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlayListPro.playlist')),
            ],
        ),
    ]
